pipeline {
    agent any
    
    stages {
        stage("build") {
            steps{
                sh "cd About-Spring; ./mvnw package"
            }
        }
        
        stage("capture") {
            steps{
                archiveArtifacts artifacts: '**/target/*.jar', followSymlinks: false
                junit '**/target/surefire-reports/TEST*.xml'   
            }
        }
    }
} 
